"""Initial schema

Revision ID: 848b60680134
Revises: 
Create Date: 2025-12-13 00:34:20.602213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848b60680134'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asri_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('asri', sa.Float(), nullable=False),
    sa.Column('asri_normalized', sa.Float(), nullable=False),
    sa.Column('asri_30d_avg', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('alert_level', sa.String(length=20), nullable=False),
    sa.Column('stablecoin_risk', sa.Float(), nullable=False),
    sa.Column('defi_liquidity_risk', sa.Float(), nullable=False),
    sa.Column('contagion_risk', sa.Float(), nullable=False),
    sa.Column('arbitrage_opacity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asri_daily_date'), 'asri_daily', ['date'], unique=True)
    op.create_index(op.f('ix_asri_daily_id'), 'asri_daily', ['id'], unique=False)
    op.create_table('raw_data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('fetch_date', sa.DateTime(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_data_sources_fetch_date'), 'raw_data_sources', ['fetch_date'], unique=False)
    op.create_index(op.f('ix_raw_data_sources_id'), 'raw_data_sources', ['id'], unique=False)
    op.create_index(op.f('ix_raw_data_sources_source'), 'raw_data_sources', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_data_sources_source'), table_name='raw_data_sources')
    op.drop_index(op.f('ix_raw_data_sources_id'), table_name='raw_data_sources')
    op.drop_index(op.f('ix_raw_data_sources_fetch_date'), table_name='raw_data_sources')
    op.drop_table('raw_data_sources')
    op.drop_index(op.f('ix_asri_daily_id'), table_name='asri_daily')
    op.drop_index(op.f('ix_asri_daily_date'), table_name='asri_daily')
    op.drop_table('asri_daily')
    # ### end Alembic commands ###
